### ISSUE TITLE
Fed v2 version hardcoded into URL for FederatedSchema

### ISSUE THREAD

**Issue by blegrosvoalte** [apollographql/federation-hotchocolate#22]
We're getting the following ever from Rover when trying to publish to a variant that supports Federation v2.4:

```
UNKNOWN_FEDERATION_LINK_VERSION: [directory] Invalid version v2.5 for the federation feature in @link direction on schema
```

Looks like the Federation version is hardcoded into the URL @ https://github.com/apollographql/federation-hotchocolate/blob/main/src/Federation/Two/FederatedSchema.cs#L10:

```
/// <summary>
/// Apollo Federation v2 base schema object that allows users to apply custom schema directives (e.g. @composeDirective)
/// </summary>
[Link("https://specs.apollo.dev/federation/v2.5", new string[] {
                "@composeDirective",
                "@extends",
                "@external",
                "@key",
                "@inaccessible",
                "@interfaceObject",
                "@override",
                "@provides",
                "@requires",
                "@shareable",
                "@tag",
                "FieldSet"
})]
```

Since the schema version is specified per variant in Apollo Studio, can we get this to be an argument to the `.AddApolloFederationV2()` method?  For example, right now we're running Router 1.19.0 which only supports Fed v2.4, so being able to specify something like the below would be helpful:

```
...

builder.Services
   .AddGraphQLServer()
   .AddApolloFederationV2('2.4')
   ...
...
```

Thoughts?

**Comment by dariuszkuc** [comment]
Hello 👋 
I've updated `FederatedSchema` to accept federation version parameter (https://github.com/apollographql/federation-hotchocolate/pull/23). Ideally we should support full `@link` capabilities (https://github.com/apollographql/federation-hotchocolate/issues/24) but that is a much bigger change....

**Comment by blegrosvoalte** [comment]
Thanks for the quick turnaround @dariuszkuc !  Appreciate the help.

**Comment by dariuszkuc** [comment]
👋 I forgot to add extension as well -> https://github.com/apollographql/federation-hotchocolate/pull/32
