### ISSUE TITLE
bug: Required External fields are not populated in Extend class

### ISSUE THREAD

**Issue by arekgwizdziel** [apollographql/federation-hotchocolate#53]
Hey,

I'm observing the same behaviour as in these two below using new Federation library:

https://github.com/ChilliCream/graphql-platform/issues/6203
https://github.com/ChilliCream/graphql-platform/issues/5891

I can see values from other subgraphs in context.Variables so I guess it's just a bug with propagating them to Extend class?

**Comment by dariuszkuc** [comment]
Hello 👋 
This appears to be working fine? I tried reproducing it locally and it seemed to work correctly (but actually uncovered a bug in our testing suite....).

Can you provide a link to a repository that reproduces this issue?

**Comment by arekgwizdziel** [comment]
Sorry for a little delay, here's the repo: https://github.com/arekgwizdziel/federation-external-bug-repro. 

The outcome below:
![Pasted image 20231114141922](https://github.com/apollographql/federation-hotchocolate/assets/150246607/a29b079a-65cc-4f60-a231-c52bb8a9f46c)

As you can see, the class field is not populated but when I traversed the Variables bucket, I can see that the data is there is _representations_ variable.

Am I misunderstanding something?

**Comment by dariuszkuc** [comment]
Hello 👋 
You need to populate the external fields from your `[ReferenceResolver]`. All those external `@requires` fields are provided when resolving the entity representation. While we are working towards simplified solution, currently when instantiating entity you need to set all those fields. See [example from compatibility project](https://github.com/apollographql/federation-hotchocolate/blob/main/Compatibility/AnnotationBased/Types/User.cs#L50).

**Comment by arekgwizdziel** [comment]
Oh, alright! I have no idea, thanks a lot for this!
