### ISSUE TITLE
Deprecation of this package?

### ISSUE THREAD

**Issue by ghost** [apollographql/federation-hotchocolate#75]
Federation V2 is now fully supported by the official HotChocolate Federation package. Does this mean this package should be deprecated and no longer be recommeded? It seems like this is no longer maintained and only the official version support the latest HotChocolate version.

It seems very misleading seeing the recommendation in this package unless I misunderstood what's going on. Can you give some clarifications on the future of this library?

Thank you

**Comment by dariuszkuc** [comment]
Apologies for the long delay. Yes, this package is now officially deprecated in favor of the built-in HC Federation module.
